name: Link Checker

on:
  pull_request:
    branches: [main]
  schedule:
    # Run nightly at 03:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    name: Check links in README and HTML
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: |
            --verbose
            --no-progress
            --cache
            --max-cache-age 1d
            README.md
            index.html
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}